# Generated by Django 5.0.1 on 2024-02-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_groups_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gs_userID",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
