# Generated by Django 5.0.1 on 2024-02-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_gs_userid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gs_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gs_password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
