# Generated by Django 5.0.2 on 2024-02-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_gs_email_user_gs_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hours",
            field=models.IntegerField(default=0),
        ),
    ]
