name: CI

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Just for running commands
        uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup NPM caching
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-lint-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-lint-
      - name: Setup pip caching
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/dev_lock.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Setup Node version 16.17
        uses: actions/setup-node@v4
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Node requirements
        run: npm ci
      - name: Install Python requirements
        run: |
          python -m pip install --upgrade setuptools wheel pip
          python -m pip install -r config/requirements/dev_lock.txt
      - name: Run linting
        run: |
          PYTHON_CMD_PREFIX="" NODE_CMD_PREFIX="" just lint
        env:
          SECRET_KEY: secret-key-for-testing-only
          DEBUG: on
          PYTHON_CMD_PREFIX_WITH_DEPS: ""
          PYTHON_CMD_PREFIX: ""
          NODE_CMD_PREFIX: ""
